# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=&oem=esse&user=c17cdf4f-a7f1-11eb-a2c5-c24e499c7467&b=true&c=px-cluster-77d61167-5b90-47f5-afe6-6f92185f6459&osft=true&stork=true&lh=true&st=k8s
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-77d61167-5b90-47f5-afe6-6f92185f6459
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=&oem=esse&user=c17cdf4f-a7f1-11eb-a2c5-c24e499c7467&b=true&c=px-cluster-77d61167-5b90-47f5-afe6-6f92185f6459&osft=true&stork=true&lh=true&st=k8s"
    portworx.io/is-openshift: "true"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:2.7.0
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  userInterface:
    enabled: true
  autopilot:
    enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: px-essential
  namespace: kube-system
data:
  px-essen-user-id: YzE3Y2RmNGYtYTdmMS0xMWViLWEyYzUtYzI0ZTQ5OWM3NDY3
  px-osb-endpoint: aHR0cHM6Ly9weGVzc2VudGlhbHMucG9ydHdvcnguY29tL29zYi9iaWxsaW5nL3YxL3JlZ2lzdGVy
