apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: EventManagerGateway
metadata:
  name: nikh-gateway-robotshop
  namespace: aiops
spec:
  logLevel: WARN
  license: accept
  objectServerPrimaryPort: 4100
  serviceAccountName: noi-service-account
  objectServerBackupPort: 4200
  kafka:
    clusterName: strimzi-cluster
    topicName: alerts-noi-1000-1000
    userName: token
  objectServerPrimaryHost: evtmanager-objserv-agg-primary
  objectServerBackupHost: evtmanager-objserv-agg-backup
  replicationTypes:
  - INSERTS
  virtualPairName: AGG_V
  filter: filter:(Severity>2) AND (AlertGroup = 'robotshop')
